/*
 * Lambda Cloud API
 * API for interacting with the Lambda GPU Cloud
 *
 * The version of the OpenAPI document: 1.5.1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for InstanceCreateInstancesRequest
 */
public class InstanceCreateInstancesRequestTest {
    private final InstanceCreateInstancesRequest model = new InstanceCreateInstancesRequest();

    /**
     * Model tests for InstanceCreateInstancesRequest
     */
    @Test
    public void testInstanceCreateInstancesRequest() {
        // TODO: test InstanceCreateInstancesRequest
    }

    /**
     * Test the property 'regionName'
     */
    @Test
    public void regionNameTest() {
        // TODO: test regionName
    }

    /**
     * Test the property 'instanceTypeName'
     */
    @Test
    public void instanceTypeNameTest() {
        // TODO: test instanceTypeName
    }

    /**
     * Test the property 'sshKeyNames'
     */
    @Test
    public void sshKeyNamesTest() {
        // TODO: test sshKeyNames
    }

    /**
     * Test the property 'fileSystemNames'
     */
    @Test
    public void fileSystemNamesTest() {
        // TODO: test fileSystemNames
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
