/*
 * Lambda Cloud API
 * API for interacting with the Lambda GPU Cloud
 *
 * The version of the OpenAPI document: 1.5.1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for InstanceCreateInstancesResponseData
 */
public class InstanceCreateInstancesResponseDataTest {
    private final InstanceCreateInstancesResponseData model = new InstanceCreateInstancesResponseData();

    /**
     * Model tests for InstanceCreateInstancesResponseData
     */
    @Test
    public void testInstanceCreateInstancesResponseData() {
        // TODO: test InstanceCreateInstancesResponseData
    }

    /**
     * Test the property 'instanceIds'
     */
    @Test
    public void instanceIdsTest() {
        // TODO: test instanceIds
    }

}
