/*
 * Lambda Cloud API
 * API for interacting with the Lambda GPU Cloud
 *
 * The version of the OpenAPI document: 1.5.1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for InstanceTypeSpecs
 */
public class InstanceTypeSpecsTest {
    private final InstanceTypeSpecs model = new InstanceTypeSpecs();

    /**
     * Model tests for InstanceTypeSpecs
     */
    @Test
    public void testInstanceTypeSpecs() {
        // TODO: test InstanceTypeSpecs
    }

    /**
     * Test the property 'vcpus'
     */
    @Test
    public void vcpusTest() {
        // TODO: test vcpus
    }

    /**
     * Test the property 'memoryGib'
     */
    @Test
    public void memoryGibTest() {
        // TODO: test memoryGib
    }

    /**
     * Test the property 'storageGib'
     */
    @Test
    public void storageGibTest() {
        // TODO: test storageGib
    }

}
