/*
 * Lambda Cloud API
 * API for interacting with the Lambda GPU Cloud
 *
 * The version of the OpenAPI document: 1.5.1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.InstanceTypeSpecs;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for InstanceType
 */
public class InstanceTypeTest {
    private final InstanceType model = new InstanceType();

    /**
     * Model tests for InstanceType
     */
    @Test
    public void testInstanceType() {
        // TODO: test InstanceType
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'priceCentsPerHour'
     */
    @Test
    public void priceCentsPerHourTest() {
        // TODO: test priceCentsPerHour
    }

    /**
     * Test the property 'specs'
     */
    @Test
    public void specsTest() {
        // TODO: test specs
    }

}
