/*
 * Lambda Cloud API
 * API for interacting with the Lambda GPU Cloud
 *
 * The version of the OpenAPI document: 1.5.1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Region;
import com.konfigthis.client.model.User;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Information about a shared file system
 */
@ApiModel(description = "Information about a shared file system")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class FileSystem {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_CREATED = "created";
  @SerializedName(SERIALIZED_NAME_CREATED)
  private String created;

  public static final String SERIALIZED_NAME_CREATED_BY = "created_by";
  @SerializedName(SERIALIZED_NAME_CREATED_BY)
  private User createdBy;

  public static final String SERIALIZED_NAME_MOUNT_POINT = "mount_point";
  @SerializedName(SERIALIZED_NAME_MOUNT_POINT)
  private String mountPoint;

  public static final String SERIALIZED_NAME_REGION = "region";
  @SerializedName(SERIALIZED_NAME_REGION)
  private Region region;

  public static final String SERIALIZED_NAME_IS_IN_USE = "is_in_use";
  @SerializedName(SERIALIZED_NAME_IS_IN_USE)
  private Boolean isInUse;

  public static final String SERIALIZED_NAME_BYTES_USED = "bytes_used";
  @SerializedName(SERIALIZED_NAME_BYTES_USED)
  private Integer bytesUsed;

  public FileSystem() {
  }

  public FileSystem id(String id) {
    
    
    
    
    this.id = id;
    return this;
  }

   /**
   * Unique identifier (ID) of a file system
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "0920582c7ff041399e34823a0be62547", required = true, value = "Unique identifier (ID) of a file system")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    
    
    
    this.id = id;
  }


  public FileSystem name(String name) {
    
    
    
    
    this.name = name;
    return this;
  }

   /**
   * Name of a file system
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "shared-fs", required = true, value = "Name of a file system")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    
    
    
    this.name = name;
  }


  public FileSystem created(String created) {
    
    
    
    
    this.created = created;
    return this;
  }

   /**
   * A date and time, formatted as an ISO 8601 time stamp
   * @return created
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "2023-02-24T20:48:56+00:00", required = true, value = "A date and time, formatted as an ISO 8601 time stamp")

  public String getCreated() {
    return created;
  }


  public void setCreated(String created) {
    
    
    
    this.created = created;
  }


  public FileSystem createdBy(User createdBy) {
    
    
    
    
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public User getCreatedBy() {
    return createdBy;
  }


  public void setCreatedBy(User createdBy) {
    
    
    
    this.createdBy = createdBy;
  }


  public FileSystem mountPoint(String mountPoint) {
    
    
    
    
    this.mountPoint = mountPoint;
    return this;
  }

   /**
   * Absolute path indicating where on instances the file system will be mounted
   * @return mountPoint
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "/home/ubuntu/shared-fs", required = true, value = "Absolute path indicating where on instances the file system will be mounted")

  public String getMountPoint() {
    return mountPoint;
  }


  public void setMountPoint(String mountPoint) {
    
    
    
    this.mountPoint = mountPoint;
  }


  public FileSystem region(Region region) {
    
    
    
    
    this.region = region;
    return this;
  }

   /**
   * Get region
   * @return region
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Region getRegion() {
    return region;
  }


  public void setRegion(Region region) {
    
    
    
    this.region = region;
  }


  public FileSystem isInUse(Boolean isInUse) {
    
    
    
    
    this.isInUse = isInUse;
    return this;
  }

   /**
   * Whether the file system is currently in use by an instance. File systems that are in use cannot be deleted.
   * @return isInUse
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Whether the file system is currently in use by an instance. File systems that are in use cannot be deleted.")

  public Boolean getIsInUse() {
    return isInUse;
  }


  public void setIsInUse(Boolean isInUse) {
    
    
    
    this.isInUse = isInUse;
  }


  public FileSystem bytesUsed(Integer bytesUsed) {
    
    
    
    
    this.bytesUsed = bytesUsed;
    return this;
  }

   /**
   * Approximate amount of storage used by the file system, in bytes. This value is an estimate that is updated every several hours.
   * @return bytesUsed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2147483648", value = "Approximate amount of storage used by the file system, in bytes. This value is an estimate that is updated every several hours.")

  public Integer getBytesUsed() {
    return bytesUsed;
  }


  public void setBytesUsed(Integer bytesUsed) {
    
    
    
    this.bytesUsed = bytesUsed;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the FileSystem instance itself
   */
  public FileSystem putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileSystem fileSystem = (FileSystem) o;
    return Objects.equals(this.id, fileSystem.id) &&
        Objects.equals(this.name, fileSystem.name) &&
        Objects.equals(this.created, fileSystem.created) &&
        Objects.equals(this.createdBy, fileSystem.createdBy) &&
        Objects.equals(this.mountPoint, fileSystem.mountPoint) &&
        Objects.equals(this.region, fileSystem.region) &&
        Objects.equals(this.isInUse, fileSystem.isInUse) &&
        Objects.equals(this.bytesUsed, fileSystem.bytesUsed)&&
        Objects.equals(this.additionalProperties, fileSystem.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, created, createdBy, mountPoint, region, isInUse, bytesUsed, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileSystem {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    mountPoint: ").append(toIndentedString(mountPoint)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    isInUse: ").append(toIndentedString(isInUse)).append("\n");
    sb.append("    bytesUsed: ").append(toIndentedString(bytesUsed)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("name");
    openapiFields.add("created");
    openapiFields.add("created_by");
    openapiFields.add("mount_point");
    openapiFields.add("region");
    openapiFields.add("is_in_use");
    openapiFields.add("bytes_used");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("created");
    openapiRequiredFields.add("created_by");
    openapiRequiredFields.add("mount_point");
    openapiRequiredFields.add("region");
    openapiRequiredFields.add("is_in_use");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to FileSystem
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!FileSystem.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in FileSystem is not found in the empty JSON string", FileSystem.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : FileSystem.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("created").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `created` to be a primitive type in the JSON string but got `%s`", jsonObj.get("created").toString()));
      }
      // validate the required field `created_by`
      User.validateJsonObject(jsonObj.getAsJsonObject("created_by"));
      if (!jsonObj.get("mount_point").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `mount_point` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mount_point").toString()));
      }
      // validate the required field `region`
      Region.validateJsonObject(jsonObj.getAsJsonObject("region"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FileSystem.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FileSystem' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FileSystem> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FileSystem.class));

       return (TypeAdapter<T>) new TypeAdapter<FileSystem>() {
           @Override
           public void write(JsonWriter out, FileSystem value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public FileSystem read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             FileSystem instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of FileSystem given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of FileSystem
  * @throws IOException if the JSON string is invalid with respect to FileSystem
  */
  public static FileSystem fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FileSystem.class);
  }

 /**
  * Convert an instance of FileSystem to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

